<?php

namespace AppBundle\Repository;

/**
 * ApiCallsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiCallsRepository extends \Doctrine\ORM\EntityRepository
{
}
